import React from 'react';
import 'react-native-gesture-handler';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import * as Localization from 'expo-localization';
import i18n from 'i18n-js';
import Home from './Home';
import Config from './Config';

i18n.translations = {
  en: { home: 'Tlush',
        config: 'Configuration', 
        hoursBtn: 'Hours', 
        salaryBtn: 'Salary',  
        sickBtn: 'Sickness',  
        vacationBtn: 'Vacation',  
        valuationBtn: 'Tax valuation',
        deductionBtn: 'Deduction',
        taxBtn: 'Tax',
        btlBtn: 'Social security',
        workBtn: 'Employer',
        workerBtn: 'Employee',
        configBtn: 'Configuration',
        calcBtn: 'Tlush',
        global: 'Global', 
        byHour: 'Hourly',
        daysWork: 'Work days',
        hours100: 'Hours 100%',
        hours125: 'Hours 125%',
        hours150: 'Hours 150%',
        hours175: 'Hours 175%',
        hours200: 'Hours 200%',
        basic: 'Base',
        extraDay: 'Daily supplement',
        extraMonth: 'Monthly supplement',
        travel: 'Daily travel',
        car: 'Car',
        phone: 'Phone',
        food: 'Meal',
        insurance: 'Medical insurance',
        present: 'Present',
        otherValuation: 'Other',
        payBtl: 'Pay to social security',
        freeBtl: 'Exemption from social security',
        payInsurance: 'Pay to health insurance',
        freeInsurance: 'Exemption from health insurance',
        kerenCeil: 'Education fund ceiling',
        keren: 'Education fund',
        rewards: 'Rewards',
        compensation: 'Compensation',
        loss: 'Loss of work capacity',
        daysSick: 'Sickness days',
        daySick1: '1 sick day',
        daySick2: '2 sick day',
        daySick3: '3 sick day',
        daysVacation: 'Vacation days',
        israelCitizen: 'Israeli citizen',
        notIsraelCitizen: 'Foreign worker',
        gender: 'Gender',
        man: 'Man',
        woman: 'Woman',
        familyStatus: 'Marital status',
        bachelor: 'Bachelor',
        married: 'Married',
        divorcee: 'Divorcee',
        widower: 'Widower',
        birthDay: 'Date of birth',
        spouseBirthDay: 'Date of birth of spouse',
        immigrationDate: 'Date of immigration',
        armyStartDate: 'Date to go to army',
        armyStopDate: 'Date of end army',
        degreeDate: 'Date of degree completion',
        addChildMyHold: 'Children in my possession',
        addChildNotMyHold: 'Children not in my possession',
        removeChildren: 'Remove children',
        child: 'Date of birth of child',
        specialTown: 'Live in unified settlement',
        spouseFoods: 'Pay alimony to spouse',
        childrenFoods: 'Pay alimony to children',
        work: 'Occupation',
        nurse: 'Nursing',
        other: 'Other',
        taxPoints: 'Tax credits',
        salary: 'Gross salary',
        valuation: 'Tax valuations',
        tax: 'Tax',
        btl: 'Social security',
        health: 'Health insurance',
        kerenWork: 'Education fund employer',
        kerenWorker: 'Education fund employee',
        rewardsWork: 'Rewards employer',
        rewardsWorker: 'Rewards employee',
        compensationWork: 'Compensation employer',
        salaryNetto: 'Net salary',
      },
  he: { home: 'תלוש',
        config: 'הגדרות', 
        hoursBtn: 'שעות', 
        salaryBtn: 'שכר',  
        sickBtn: 'מחלה',  
        vacationBtn: 'חופש',  
        valuationBtn: 'שווי מס',
        deductionBtn: 'ניכויים',
        taxBtn: 'מס הכנסה',
        btlBtn: 'ביטוח לאומי',
        workBtn: 'מעביד',
        workerBtn: 'עובד',
        configBtn: 'הגדרות',
        calcBtn: 'תלוש',
        global: 'גלובלי', 
        byHour: 'לפי שעה',
        daysWork: 'ימי עבודה',
        hours100: 'שעות 100%',
        hours125: 'שעות 125%',
        hours150: 'שעות 150%',
        hours175: 'שעות 175%',
        hours200: 'שעות 200%',
        basic: 'בסיס',
        extraDay: 'תוספת יומית',
        extraMonth: 'תוספת חודשית',
        travel: 'נסיעות יומית',
        car: 'רכב',
        phone: 'טלפון',
        food: 'ארוחות',
        insurance: 'ביטוח רפואי',
        present: 'מתנות',
        otherValuation: 'אחר',
        payBtl: 'משלם ביטוח לאומי',
        freeBtl: 'פטור מתשלום ביטוח לאומי',
        payInsurance: 'משלם ביטוח בריאות',
        freeInsurance: 'פטור מתשלום ביטוח בריאות',
        kerenCeil: 'תקרת קרן השתלמות',
        keren: 'קרן השתלמות',
        rewards: 'תיגמולים',
        compensation: 'פיצויים',
        loss: 'אובדן כושר עבודה',
        daysSick: 'ימי מחלה',
        daySick1: 'יום מחלה 1',
        daySick2: 'יום מחלה 2',
        daySick3: 'יום מחלה 3',
        daysVacation: 'ימי חופש',
        israelCitizen: 'אזרח ישראלי',
        notIsraelCitizen: 'עובד זר',
        gender: 'מין',
        man: 'זכר',
        woman: 'נקבה',
        familyStatus: 'מצב משפחתי',
        bachelor: 'רווק/ה',
        married: 'נשוי/אה',
        divorcee: 'גרוש/ה',
        widower: 'אלמן/ה',
        birthDay: 'תאריך לידה',
        spouseBirthDay: 'תאריך לידה בן זוג',
        immigrationDate: 'תאריך עליה',
        armyStartDate: 'תאריך גיוס',
        armyStopDate: 'תאריך שיחרור',
        degreeDate: 'תאריך סיום תואר',
        addChildMyHold: 'ילדים בחזקתי',
        addChildNotMyHold: 'ילדים לא בחזקתי',
        removeChildren: 'למחוק ילדים',
        child: 'תאריך לידה ילד',
        specialTown: 'גר בישוב מאוחד',
        spouseFoods: 'משלם מזונות לבן זוג',
        childrenFoods: 'משלם מזונות לילדים',
        work: 'עיסוק',
        nurse: 'סיעוד',
        other: 'אחר',
        taxPoints: 'נקודות זיכוי',
        salary: 'משכורת ברוטו',
        valuation: 'שווי מס',
        tax: 'מס הכנסה',
        btl: 'ביטוח לאומי',
        health: 'ביטוח בריאות',
        kerenWork: 'קרן השתלמות מעביד',
        kerenWorker: 'קרן השתלמות עובד',
        rewardsWork: 'פנסיה מעביד',
        rewardsWorker: 'פנסיה עובד',
        compensationWork: 'פיצויים מעביד',
        salaryNetto: 'משכורת נטו',
      },
  ru: { home: 'Тлюш',
        config: 'Конфигурация', 
        hoursBtn: 'Часы', 
        salaryBtn: 'Зарплата',  
        sickBtn: 'Болезнь',  
        vacationBtn: 'Отпуск',  
        valuationBtn: 'Налоговые оценки', 
        deductionBtn: 'Выплаты',
        taxBtn: 'Налог',
        btlBtn: 'Национальное страхование',
        workBtn: 'Работодатель',
        workerBtn: 'Работник',
        configBtn: 'Конфигурация',
        calcBtn: 'Тлюш',
        global: 'Глобальная', 
        byHour: 'Почасовая',
        daysWork: 'Рабочих дней',
        hours100: 'Часы 100%',
        hours125: 'Часы 125%',
        hours150: 'Часы 150%',
        hours175: 'Часы 175%',
        hours200: 'Часы 200%',
        basic: 'Базовая оплата',
        extraDay: 'Экстра дневная оплата',
        extraMonth: 'Экстра месячная оплата',
        travel: 'Ежедневный проезд',
        car: 'Автомобиль',
        phone: 'Телефон',
        food: 'Питание',
        insurance: 'Страховка',
        present: 'Подарки',
        otherValuation: 'Другое',
        payBtl: 'Плачу страхование',
        freeBtl: 'Освобождение от страхования',
        payInsurance: 'Плачу в больничную кассу',
        freeInsurance: 'Освобождение от больничной кассы',
        kerenCeil: 'Потолок в фонд обучения',
        keren: 'Фонд обучения',
        rewards: 'Пенсия',
        compensation: 'Компенсация',
        loss: 'Потеря трудоспособности',
        daysSick: 'Болезненных дней',
        daySick1: '1 день болезни',
        daySick2: '2 день болезни',
        daySick3: '3 день болезни',
        daysVacation: 'Отпускных дней',
        israelCitizen: 'Гражданин Израиля',
        notIsraelCitizen: 'Иностранный рабочий',
        gender: 'Пол',
        man: 'Мужчина',
        woman: 'Женщина',
        familyStatus: 'Семейное положение',
        bachelor: 'Одиночка',
        married: 'Женат/Замужем',
        divorcee: 'Разведён/а',
        widower: 'Вдовец/Вдова',
        birthDay: 'Дата рождения',
        spouseBirthDay: 'Дата рождения супруга',
        immigrationDate: 'Дата иммиграции',
        armyStartDate: 'Дата призыва в армию',
        armyStopDate: 'Дата освобождения из армии',
        degreeDate: 'Дата завершения диплома',
        addChildMyHold: 'Дети со мной',
        addChildNotMyHold: 'Дети не со мной',
        removeChildren: 'Стереть детей',
        child: 'Дата рождения ребёнка',
        specialTown: 'Проживаю в городе развития',
        spouseFoods: 'Плачу элементы бывшему супругу',
        childrenFoods: 'Плачу элементы детям',
        work: 'Занятость',
        nurse: 'Уход',
        other: 'Другое',
        taxPoints: 'Налоговые кредиты',
        salary: 'Грязная зарплата',
        valuation: 'Налоговые оценки',
        tax: 'Налог',
        btl: 'Национальное страхование',
        health: 'Медицинское страхование',
        kerenWork: 'Работодатель в фонд обучения',
        kerenWorker: 'Работник в фонд обучения',
        rewardsWork: 'Работодатель на пенсию',
        rewardsWorker: 'Работник на пенсию',
        compensationWork: 'Работодатель на компенсацию',
        salaryNetto: 'Чистая зарплата',
      },
};
// Set the locale once at the beginning of your app.
i18n.locale = Localization.locale;
// When a value is missing from a language it'll fallback to another language with the key present.
i18n.fallbacks = true;

const Stack = createStackNavigator();

const App = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={Home} options={{ title: i18n.t('home') }} />
        <Stack.Screen name="Config" component={Config} options={{ title: i18n.t('config') }} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}


export default App;
